const {
  NODE_ENV = 'production',
  PORT = 4000,
  MONGO_URI = '',
  JWT_ACCESS_SECRET = '',
  JWT_ACCESS_EXPIRES_IN = '15m',
  CORS_WHITELIST = '',
  EMAIL_HOST = '',
  EMAIL_PORT = '',
  EMAIL_SECURE = '',
  EMAIL_USER = '',
  EMAIL_PASSWORD = '',
  EMAIL_FROM = '',
  FRONTEND_URL = '',
  TWILIO_ACCOUNT_SID = '',
  TWILIO_AUTH_TOKEN = '',
  TWILIO_VERIFY_SERVICE_SID = '',
  TWILIO_FROM_NUMBER = '',
  TWILIO_WHATSAPP_FROM = '',
  TWILIO_WHATSAPP_TEMPLATE_SID = '',
  TWILIO_MESSAGING_SERVICE_SID = '',
  OTP_TOKEN_SECRET = '',
  OTP_TOKEN_EXPIRES_IN = '10m',
} = process.env;

module.exports = {
  apps: [{
    name: 'customer-support-api',
    script: 'src/server.js',
    instances: 'max',
    exec_mode: 'cluster',
    env: {
      NODE_ENV,
      PORT,
      MONGO_URI,
      JWT_ACCESS_SECRET,
      JWT_ACCESS_EXPIRES_IN,
      CORS_WHITELIST,
      EMAIL_HOST,
      EMAIL_PORT,
      EMAIL_SECURE,
      EMAIL_USER,
      EMAIL_PASSWORD,
      EMAIL_FROM,
      FRONTEND_URL,
      TWILIO_ACCOUNT_SID,
      TWILIO_AUTH_TOKEN,
      TWILIO_VERIFY_SERVICE_SID,
      TWILIO_FROM_NUMBER,
      TWILIO_WHATSAPP_FROM,
      TWILIO_WHATSAPP_TEMPLATE_SID,
      TWILIO_MESSAGING_SERVICE_SID,
      OTP_TOKEN_SECRET,
      OTP_TOKEN_EXPIRES_IN,
    },
    error_file: './logs/err.log',
    out_file: './logs/out.log',
    log_file: './logs/combined.log',
    time: true,
    max_memory_restart: '1G',
    restart_delay: 4000,
    max_restarts: 10,
    min_uptime: '10s'
  }]
};
