name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Frontend deployments removed - this is backend repository only
  # Frontend should be deployed from separate repositories

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 10m
        script: |
          echo "Connected to EC2 successfully!"
          pwd
          ls -la
          echo "Checking if project directory exists..."
          if [ -d "/home/ec2-user/customer-support" ]; then
            echo "Project directory found, updating..."
            cd /home/ec2-user/customer-support
            git pull origin main
            npm install
            pm2 restart all
            echo "Deployment completed successfully!"
          else
            echo "Project directory not found, creating..."
            mkdir -p /home/ec2-user/customer-support
            cd /home/ec2-user
            git clone https://github.com/alok-0404/Customer_support.git customer-support
            cd customer-support
            npm install
            pm2 start ecosystem.config.js
            echo "Initial deployment completed!"
          fi
